name: Deploy Sphinx Documentation

on:
  push:
    branches: [ main ]  # Change to your default branch if different
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        # Add any other dependencies your docs need
        # pip install sphinx-rtd-theme  # if you use RTD theme
        # pip install -r docs/requirements.txt  # if you have a requirements file
        
    - name: Build documentation
      run: |
        cd docs
        make html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'  # Only deploy on main branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
